<a href="https://colab.research.google.com/github/lissettzuniga/data-science-course/blob/main/inmuebles_cdmx.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Pandas**

# **Importando la Base de Datos**

In [2]:
import pandas as pd
url = 'https://gist.githubusercontent.com/ahcamachod/a572cfcc2527046db93101f88011b26e/raw/ffb13f45a79d31223e645611a119397dd127ee3c/alquiler.csv'
pd.read_csv(url)

      Tipo;Colonia;Habitaciones;Garages;Suites;Area;Valor;Condominio;Impuesto
0          Cocineta;Condesa;1;0;0;40;5950.0;1750.0;210.0
1                       Casa;Polanco;2;0;1;100;24500.0;;
2      Conjunto Comercial/Sala;Santa Fe;0;4;0;150;182...
3      Departamento;Centro Histórico;1;0;0;15;2800.0;...
4          Departamento;Del Valle;1;0;0;48;2800.0;805.0;
...                                                  ...
25116  Cochera/Estacionamiento;Centro Histórico;0;0;0...
25117  Cocineta;Centro Histórico;0;0;0;27;2800.0;1225...
25118  Departamento;Mixcoac;2;1;0;48;4900.0;1781.5;129.5
25119  Departamento;Lomas de Chapultepec;2;0;0;70;105...
25120  Conjunto Comercial/Sala;Centro Histórico;0;0;0...

[25121 rows x 1 columns]

In [3]:
pd.read_csv(url, sep=';')

,Tipo,Colonia,Habitaciones,Garages,Suites,Area,Valor,Condominio,Impuesto
0,Cocineta,Condesa,1,0,0,40,5950.0,1750.0,210.0
1,Casa,Polanco,2,0,1,100,24500.0,NaN,NaN
2,Conjunto Comercial/Sala,Santa Fe,0,4,0,150,18200.0,14070.0,3888.5
3,Departamento,Centro Histórico,1,0,0,15,2800.0,1365.0,70.0
4,Departamento,Del Valle,1,0,0,48,2800.0,805.0,NaN
...,...,...,...,...,...,...,...,...,...
25116,Cochera/Estacionamiento,Centro Histórico,0,0,0,755,49000.0,NaN,NaN
25117,Cocineta,Centro Histórico,0,0,0,27,2800.0,1225.0,87.5
25118,Departamento,Mixcoac,2,1,0,48,4900.0,1781.5,129.5
25119,Departamento,Lomas de Chapultepec,2,0,0,70,10500.0,2660.0,NaN
25120,Conjunto Comercial/Sala,Centro Histórico,0,0,0,250,22750.0,14721.0,3881.5

In [5]:
datos = pd.read_csv(url, sep=';')
datos

,Tipo,Colonia,Habitaciones,Garages,Suites,Area,Valor,Condominio,Impuesto
0,Cocineta,Condesa,1,0,0,40,5950.0,1750.0,210.0
1,Casa,Polanco,2,0,1,100,24500.0,NaN,NaN
2,Conjunto Comercial/Sala,Santa Fe,0,4,0,150,18200.0,14070.0,3888.5
3,Departamento,Centro Histórico,1,0,0,15,2800.0,1365.0,70.0
4,Departamento,Del Valle,1,0,0,48,2800.0,805.0,NaN
...,...,...,...,...,...,...,...,...,...
25116,Cochera/Estacionamiento,Centro Histórico,0,0,0,755,49000.0,NaN,NaN
25117,Cocineta,Centro Histórico,0,0,0,27,2800.0,1225.0,87.5
25118,Departamento,Mixcoac,2,1,0,48,4900.0,1781.5,129.5
25119,Departamento,Lomas de Chapultepec,2,0,0,70,10500.0,2660.0,NaN
25120,Conjunto Comercial/Sala,Centro Histórico,0,0,0,250,22750.0,14721.0,3881.5

In [6]:
datos.head()

,Tipo,Colonia,Habitaciones,Garages,Suites,Area,Valor,Condominio,Impuesto
0,Cocineta,Condesa,1,0,0,40,5950.0,1750.0,210.0
1,Casa,Polanco,2,0,1,100,24500.0,NaN,NaN
2,Conjunto Comercial/Sala,Santa Fe,0,4,0,150,18200.0,14070.0,3888.5
3,Departamento,Centro Histórico,1,0,0,15,2800.0,1365.0,70.0
4,Departamento,Del Valle,1,0,0,48,2800.0,805.0,NaN

In [7]:
datos.tail()

,Tipo,Colonia,Habitaciones,Garages,Suites,Area,Valor,Condominio,Impuesto
25116,Cochera/Estacionamiento,Centro Histórico,0,0,0,755,49000.0,NaN,NaN
25117,Cocineta,Centro Histórico,0,0,0,27,2800.0,1225.0,87.5
25118,Departamento,Mixcoac,2,1,0,48,4900.0,1781.5,129.5
25119,Departamento,Lomas de Chapultepec,2,0,0,70,10500.0,2660.0,NaN
25120,Conjunto Comercial/Sala,Centro Histórico,0,0,0,250,22750.0,14721.0,3881.5

In [8]:
type(datos)

pandas.core.frame.DataFrame

## **Exploración inicial de los datos**

In [9]:
datos.sample(5)

,Tipo,Colonia,Habitaciones,Garages,Suites,Area,Valor,Condominio,Impuesto
9221,Departamento,Condesa,3,2,1,159,26250.0,4259.5,1613.5
8544,Departamento,Roma,1,1,1,45,9100.0,3500.0,NaN
22381,Conjunto Comercial/Sala,Santa Fe,0,4,0,132,28000.0,13419.0,4350.5
21231,Edificio Completo,La Condesa,0,11,0,2500,525000.0,NaN,NaN
4594,Conjunto Comercial/Sala,Santa Fe,0,3,0,30,12250.0,9009.0,2023.0

In [11]:
datos.shape

(25121, 9)

In [12]:
datos.columns

Index(['Tipo', 'Colonia', 'Habitaciones', 'Garages', 'Suites', 'Area', 'Valor',
       'Condominio', 'Impuesto'],
      dtype='object')

In [14]:
datos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25121 entries, 0 to 25120
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Tipo          25121 non-null  object
 1   Colonia       25121 non-null  object
 2   Habitaciones  25121 non-null  int64
 3   Garages       25121 non-null  int64
 4   Suites        25121 non-null  int64
 5   Area          25121 non-null  int64
 6   Valor         25107 non-null  float64
 7   Condominio    22495 non-null  float64
 8   Impuesto      18037 non-null  float64
dtypes: float64(3), int64(4), object(2)
memory usage: 1.7+ MB

In [15]:
import pandas as pd
url = 'https://gist.githubusercontent.com/ahcamachod/807a2c1cf6c19108b2b701ea1791ab45/raw/fb84f8b2d8917a89de26679eccdbc8f9c1d2e933/alumnos.csv'
datos = pd.read_csv(url)

In [17]:
datos.head(7)

    Nombre  Edad  Nota Aprobado
0  Alberto    20   7.5     True
1      Ana    18   NaN    False
2   Camila    27   2.5    False
3    David    18   5.0    False
4    Brian    21  10.0     True
5    Bruna    23   NaN    False
6  Daniela    21   7.0     True

In [18]:
datos.tail()

    Nombre  Edad  Nota   Aprobado
13  Miriam    25   9.0       True
14   Pablo    37   NaN      False
15  Milena    29   7.0       True
16   Lucas    33   NaN      False
17   Nadia    34   8.0  Verdadero

In [19]:
# Visualizar los nombres de las columnas
datos.columns

# Seleccionar una columna
datos['Nombre']

# Seleccionar múltiples columnas
datos[['Edad', 'Nota']]

# Verificar los tipos de datos en cada columna
datos.dtypes

Nombre       object
Edad          int64
Nota        float64
Aprobado     object
dtype: object

In [20]:
datos.describe()

            Edad       Nota
count  18.000000  12.000000
mean   25.500000   6.841667
std     6.070662   2.264532
min    18.000000   2.500000
25%    21.000000   5.450000
50%    24.500000   7.000000
75%    28.750000   8.250000
max    37.000000  10.000000